"""empty message

Revision ID: 71256e84abb2
Revises: 
Create Date: 2021-11-26 12:16:09.662737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71256e84abb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('meal',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('meal_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('meal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal')
    op.drop_table('food')
    # ### end Alembic commands ###
